# Generated by Django 2.1.4 on 2019-11-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('function_id', models.AutoField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=32, verbose_name='职能名称')),
            ],
            options={
                'db_table': 'function',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='技能名称')),
                ('skill_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='技能类型')),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='SkillFunction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_id', models.IntegerField(verbose_name='技能id')),
                ('function_id', models.IntegerField(verbose_name='职能id')),
            ],
            options={
                'db_table': 'skillFunction',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=32, verbose_name='团队名称')),
                ('team_comment', models.TextField(blank=True, null=True, verbose_name='简介')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TeamFunction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField(verbose_name='团队id')),
                ('function_id', models.IntegerField(verbose_name='职能id')),
            ],
            options={
                'db_table': 'teamFunction',
            },
        ),
    ]
