# Generated by Django 2.1.4 on 2019-11-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamskillstack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeberRole',
            fields=[
                ('member_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_member_id', models.IntegerField(verbose_name='团队成员id')),
                ('role_id', models.IntegerField(verbose_name='角色id')),
            ],
            options={
                'db_table': 'memeberRole',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=50, verbose_name='权限名称')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='PermissionRole',
            fields=[
                ('per_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_id', models.IntegerField(verbose_name='权限id')),
                ('role_id', models.IntegerField(verbose_name='角色id')),
            ],
            options={
                'db_table': 'permissionRole',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20, verbose_name='角色名称')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='TeamMemeber',
            fields=[
                ('team_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField(verbose_name='团队id')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
            ],
            options={
                'db_table': 'teamMemeber',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('icon', models.CharField(blank=True, max_length=150, null=True, verbose_name='头像')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('role_id', models.IntegerField(verbose_name='角色id')),
            ],
            options={
                'db_table': 'userRole',
            },
        ),
    ]
