# Generated by Django 2.1.4 on 2019-11-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamskillstack', '0002_memeberrole_permission_permissionrole_role_teammemeber_user_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='function_comment',
            field=models.TextField(blank=True, null=True, verbose_name='介绍'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_creator',
            field=models.IntegerField(blank=True, null=True, verbose_name='团队创建者'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='用户名'),
        ),
    ]
